-- Phase 3 of the canonical catalog (catalog/docs/roadmap.md, step 3.2): normalized attributes and detail status.
--
-- catalog/config/attribute_schema.yaml defines, per group of products, the attributes a listing can be autofilled
-- with and which of them are required for a product to count as detailed. catalog/src/laria_catalog/details.py
-- resolves them on every ETL run from the raw per-source specs, the catalog category and explicit words in product
-- names. catalog_product_attributes holds one resolved value per (product, attribute) and is regenerated by the
-- loader; the raw evidence stays in catalog_product_specs.
--
-- Depends on 20260927120000_canonical_catalog.sql.

-- ------------------------------------------------------------------ products: detail status
alter table public.catalog_products
  add column if not exists detail_group text,
  add column if not exists detail_status text not null default 'out_of_scope',
  add column if not exists missing_attributes text[] not null default '{}',
  add column if not exists untrusted_attributes text[] not null default '{}';

alter table public.catalog_products drop constraint if exists catalog_products_detail_status_check;
alter table public.catalog_products add constraint catalog_products_detail_status_check
  check (detail_status in ('out_of_scope', 'none', 'partial', 'complete', 'detailed'));

comment on column public.catalog_products.detail_group is
  'Attribute group of catalog/config/attribute_schema.yaml (a marketplace instrument type, or keyboards); null = no group.';
comment on column public.catalog_products.detail_status is
  'out_of_scope (no required attributes) | none | partial | complete (all required values present, some untrusted or in conflict, or not publish_ready) | detailed.';
comment on column public.catalog_products.missing_attributes is 'Required attributes without a value.';
comment on column public.catalog_products.untrusted_attributes is
  'Required attributes whose value is untrusted (weak single source) or contradicted by another strong candidate.';

create index if not exists catalog_products_detail_idx on public.catalog_products (detail_group, detail_status);

-- ------------------------------------------------------------------ resolved attributes
create table if not exists public.catalog_product_attributes (
  id uuid primary key,
  product_id uuid not null references public.catalog_products(id) on delete cascade,
  attribute_key text not null,
  value text not null,                              -- enum value, number, 'true'/'false', or a JSON list
  value_num numeric,
  unit text,
  provenance text not null check (provenance in ('spec', 'category', 'name', 'derived')),
  sources text[] not null default '{}',             -- independent source groups (or category / name / series) backing the value
  weight numeric not null,                          -- best candidate weight (confidence.py authority weights)
  trusted boolean not null default false,           -- weight >= 0.70 or 2+ agreeing sources, and no strong disagreement
  conflict_values text[] not null default '{}',     -- other values from strong candidates
  created_at timestamptz not null default now(),
  unique (product_id, attribute_key)
);
create index if not exists catalog_product_attributes_key_idx on public.catalog_product_attributes (attribute_key, value);

comment on table public.catalog_product_attributes is
  'One normalized value per (product, attribute) of catalog/config/attribute_schema.yaml, resolved by the catalog ETL. Regenerated on every load.';

-- Catalog reference data is public read-only; writes happen through the service role (ETL) only.
alter table public.catalog_product_attributes enable row level security;
drop policy if exists "catalog_product_attributes public read" on public.catalog_product_attributes;
create policy "catalog_product_attributes public read" on public.catalog_product_attributes
  for select to anon, authenticated using (true);
